extends Node

const TILE_SIZE = 24
const WORLD_CENTER = Vector2i(512 / 24 / 2, 288 / 24 / 2)
const WORLD_BOUNDS = Vector2i(15, 10)
const WORLD_CAMERA_BOUNDS = Vector2i(25, 20)

const TILE_GRASS = 1
const TILE_WATER = 0

enum Layer { WATER, GRASS, P1, P2, P3 }
const NO_TEAM = 0
const TEAM_COLORS = [0xffffffff, 0xff776eff, 0x6effff, 0xfdff6eff]

const TURN_TIME = 0.25

const NEIGHBORS = [
	TileSet.CELL_NEIGHBOR_RIGHT_SIDE,
	TileSet.CELL_NEIGHBOR_BOTTOM_LEFT_SIDE,
	TileSet.CELL_NEIGHBOR_BOTTOM_RIGHT_SIDE,
	TileSet.CELL_NEIGHBOR_LEFT_SIDE,
	TileSet.CELL_NEIGHBOR_TOP_LEFT_SIDE,
	TileSet.CELL_NEIGHBOR_TOP_RIGHT_SIDE
]

const NO_BORDERS = {
	TileSet.CELL_NEIGHBOR_RIGHT_SIDE: false,
	TileSet.CELL_NEIGHBOR_BOTTOM_LEFT_SIDE: false,
	TileSet.CELL_NEIGHBOR_BOTTOM_RIGHT_SIDE: false,
	TileSet.CELL_NEIGHBOR_LEFT_SIDE: false,
	TileSet.CELL_NEIGHBOR_TOP_LEFT_SIDE: false,
	TileSet.CELL_NEIGHBOR_TOP_RIGHT_SIDE: false
}

const FULL_BORDERS = {
	TileSet.CELL_NEIGHBOR_RIGHT_SIDE: true,
	TileSet.CELL_NEIGHBOR_BOTTOM_LEFT_SIDE: true,
	TileSet.CELL_NEIGHBOR_BOTTOM_RIGHT_SIDE: true,
	TileSet.CELL_NEIGHBOR_LEFT_SIDE: true,
	TileSet.CELL_NEIGHBOR_TOP_LEFT_SIDE: true,
	TileSet.CELL_NEIGHBOR_TOP_RIGHT_SIDE: true
}

const NO_REGION = -99

enum Action { NONE, MOVE }
