extends Node

const DEFAULT_TEAMS_ALIVE: float = 0.16
const DEFAULT_REGIONS: float = 0.16
const DEFAULT_TILES: float = 0.16
const DEFAULT_UNITS: float = 0.16
const DEFAULT_LANDLOCKED: float = 0.16
const DEFAULT_DISTANCE: float = 0.16
var DEFAULT_PERSONALITY = BotPersonality.new(DEFAULT_TEAMS_ALIVE, DEFAULT_REGIONS, DEFAULT_TILES,
	DEFAULT_UNITS, DEFAULT_LANDLOCKED, DEFAULT_DISTANCE)

const AGGRESSIVE_TEAMS_ALIVE: float = 0.3
const AGGRESSIVE_REGIONS: float = 0.3
const AGGRESSIVE_TILES: float = 0.1
const AGGRESSIVE_UNITS: float = 0
const AGGRESSIVE_LANDLOCKED: float = 0.15
const AGGRESSIVE_DISTANCE: float = 0.15
var AGGRESSIVE_PERSONALITY = BotPersonality.new(AGGRESSIVE_TEAMS_ALIVE, AGGRESSIVE_REGIONS, AGGRESSIVE_TILES,
	AGGRESSIVE_UNITS, AGGRESSIVE_LANDLOCKED, AGGRESSIVE_DISTANCE)

const DEFENSIVE_TEAMS_ALIVE: float = 0.067
const DEFENSIVE_REGIONS: float = 0.067
const DEFENSIVE_TILES: float = 0.067
const DEFENSIVE_UNITS: float = 0.4
const DEFENSIVE_LANDLOCKED: float = 0.2
const DEFENSIVE_DISTANCE: float = 0.2
var DEFENSIVE_PERSONALITY = BotPersonality.new(DEFENSIVE_TEAMS_ALIVE, DEFENSIVE_REGIONS, DEFENSIVE_TILES,
	DEFENSIVE_UNITS, DEFENSIVE_LANDLOCKED, DEFENSIVE_DISTANCE)

var TEAM_PERSONALITIES = [
	null,  # no team
	null,  # blue
	AGGRESSIVE_PERSONALITY,  # orange
	DEFENSIVE_PERSONALITY,  # pink
	DEFAULT_PERSONALITY,  # yellow
	DEFAULT_PERSONALITY,  # red
	DEFAULT_PERSONALITY,  # green
	DEFAULT_PERSONALITY,  # grey
	DEFAULT_PERSONALITY,  # purple
	DEFAULT_PERSONALITY,  # cyan
	DEFAULT_PERSONALITY,  # lime
]